apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cronjob
            image: PROJECT/IMAGE
          restartPolicy: OnFailure